package com.upg;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-01-27T20:33:28.516+03:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://upg.sbns.bssys.com/", name = "UniversalPaymentGateSbrf")
@XmlSeeAlso({ObjectFactory.class})
public interface UniversalPaymentGateSbrf {

    @WebMethod
    @RequestWrapper(localName = "getIdCookie", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.GetIdCookie")
    @ResponseWrapper(localName = "getIdCookieResponse", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.GetIdCookieResponse")
    @WebResult(name = "return", targetNamespace = "http://upg.sbns.bssys.com/")
    public java.lang.String getIdCookie(
            @WebParam(name = "sessionId", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String sessionId,
            @WebParam(name = "SID2", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String sid2
    );

    @WebMethod
    @RequestWrapper(localName = "sendRequestZip", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.SendRequestZip")
    @ResponseWrapper(localName = "sendRequestZipResponse", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.SendRequestZipResponse")
    @WebResult(name = "return", targetNamespace = "http://upg.sbns.bssys.com/")
    public java.lang.String sendRequestZip(
            @WebParam(name = "zipRequest", targetNamespace = "http://upg.sbns.bssys.com/")
                    byte[] zipRequest,
            @WebParam(name = "orgId", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String orgId,
            @WebParam(name = "requestId", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String requestId,
            @WebParam(name = "customsCardId", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String customsCardId,
            @WebParam(name = "customsOperatorId", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String customsOperatorId,
            @WebParam(name = "sessionId", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String sessionId,
            @WebParam(name = "clientOrgId", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String clientOrgId
    );

    @WebMethod
    @RequestWrapper(localName = "logout", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.LogoutResponse")
    @WebResult(name = "return", targetNamespace = "http://upg.sbns.bssys.com/")
    public java.lang.String logout(
            @WebParam(name = "sessionId", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String sessionId
    );

    @WebMethod
    @RequestWrapper(localName = "getResponsePart", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.GetResponsePart")
    @ResponseWrapper(localName = "getResponsePartResponse", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.GetResponsePartResponse")
    @WebResult(name = "return", targetNamespace = "http://upg.sbns.bssys.com/")
    public java.lang.String getResponsePart(
            @WebParam(name = "request", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String request,
            @WebParam(name = "part", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String part,
            @WebParam(name = "orgId", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String orgId
    );

    @WebMethod
    @RequestWrapper(localName = "getRequestStatus", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.GetRequestStatus")
    @ResponseWrapper(localName = "getRequestStatusResponse", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.GetRequestStatusResponse")
    @WebResult(name = "return", targetNamespace = "http://upg.sbns.bssys.com/")
    public java.util.List<java.lang.String> getRequestStatus(
            @WebParam(name = "requests", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.util.List<java.lang.String> requests,
            @WebParam(name = "orgId", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String orgId
    );

    @WebMethod
    @RequestWrapper(localName = "sendRequests", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.SendRequests")
    @ResponseWrapper(localName = "sendRequestsResponse", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.SendRequestsResponse")
    @WebResult(name = "return", targetNamespace = "http://upg.sbns.bssys.com/")
    public java.util.List<java.lang.String> sendRequests(
            @WebParam(name = "requests", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.util.List<java.lang.String> requests
    );

    @WebMethod
    @RequestWrapper(localName = "verifySMSSession", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.VerifySMSSession")
    @ResponseWrapper(localName = "verifySMSSessionResponse", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.VerifySMSSessionResponse")
    @WebResult(name = "return", targetNamespace = "http://upg.sbns.bssys.com/")
    public byte[] verifySMSSession(
            @WebParam(name = "sessionId", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String sessionId,
            @WebParam(name = "smsCode", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String smsCode
    );

    @WebMethod
    @RequestWrapper(localName = "getResponsePartSRP", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.GetResponsePartSRP")
    @ResponseWrapper(localName = "getResponsePartSRPResponse", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.GetResponsePartSRPResponse")
    @WebResult(name = "return", targetNamespace = "http://upg.sbns.bssys.com/")
    public java.lang.String getResponsePartSRP(
            @WebParam(name = "request", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String request,
            @WebParam(name = "part", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String part,
            @WebParam(name = "sessionId", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String sessionId,
            @WebParam(name = "orgId", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String orgId
    );

    @WebMethod
    @RequestWrapper(localName = "getRequestStatusSRP", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.GetRequestStatusSRP")
    @ResponseWrapper(localName = "getRequestStatusSRPResponse", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.GetRequestStatusSRPResponse")
    @WebResult(name = "return", targetNamespace = "http://upg.sbns.bssys.com/")
    public java.util.List<java.lang.String> getRequestStatusSRP(
            @WebParam(name = "requests", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.util.List<java.lang.String> requests,
            @WebParam(name = "sessionId", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String sessionId,
            @WebParam(name = "orgId", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String orgId
    );

    @WebMethod
    @RequestWrapper(localName = "preChangePassword", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.PreChangePassword")
    @ResponseWrapper(localName = "preChangePasswordResponse", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.PreChangePasswordResponse")
    @WebResult(name = "return", targetNamespace = "http://upg.sbns.bssys.com/")
    public java.util.List<byte[]> preChangePassword(
            @WebParam(name = "sessionId", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String sessionId
    );

    @WebMethod
    @RequestWrapper(localName = "login", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.LoginResponse")
    @WebResult(name = "return", targetNamespace = "http://upg.sbns.bssys.com/")
    public java.util.List<byte[]> login(
            @WebParam(name = "sessionId", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String sessionId,
            @WebParam(name = "clientAuthData", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.util.List<byte[]> clientAuthData
    );

    @WebMethod
    @RequestWrapper(localName = "sendDocumentReceipts", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.SendDocumentReceipts")
    @ResponseWrapper(localName = "sendDocumentReceiptsResponse", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.SendDocumentReceiptsResponse")
    @WebResult(name = "return", targetNamespace = "http://upg.sbns.bssys.com/")
    public java.util.List<java.lang.String> sendDocumentReceipts(
            @WebParam(name = "receipt", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.util.List<java.lang.String> receipt,
            @WebParam(name = "sessionId", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String sessionId
    );

    @WebMethod
    @RequestWrapper(localName = "sendPcHash", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.SendPcHash")
    @ResponseWrapper(localName = "sendPcHashResponse", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.SendPcHashResponse")
    @WebResult(name = "return", targetNamespace = "http://upg.sbns.bssys.com/")
    public java.lang.String sendPcHash(
            @WebParam(name = "sessionId", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String sessionId,
            @WebParam(name = "pcHash", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String pcHash
    );

    @WebMethod
    @RequestWrapper(localName = "changePassword", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.ChangePassword")
    @ResponseWrapper(localName = "changePasswordResponse", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.ChangePasswordResponse")
    @WebResult(name = "return", targetNamespace = "http://upg.sbns.bssys.com/")
    public java.util.List<byte[]> changePassword(
            @WebParam(name = "sessionId", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String sessionId,
            @WebParam(name = "newPasswordData", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.util.List<byte[]> newPasswordData
    );

    @WebMethod
    @RequestWrapper(localName = "preLogin", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.PreLogin")
    @ResponseWrapper(localName = "preLoginResponse", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.PreLoginResponse")
    @WebResult(name = "return", targetNamespace = "http://upg.sbns.bssys.com/")
    public java.util.List<byte[]> preLogin(
            @WebParam(name = "userLogin", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String userLogin,
            @WebParam(name = "changePassword", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.Boolean changePassword
//        @WebParam(name = "senderKey", targetNamespace = "http://upg.sbns.bssys.com/")
//        java.lang.String senderKey
    );

    @WebMethod
    @RequestWrapper(localName = "preLoginSign", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.PreLoginSign")
    @ResponseWrapper(localName = "preLoginSignResponse", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.PreLoginSignResponse")
    @WebResult(name = "return", targetNamespace = "http://upg.sbns.bssys.com/")
    public java.util.List<byte[]> preLoginSign(
            @WebParam(name = "serial", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String serial,
            @WebParam(name = "issue", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String issue
//            ,
//        @WebParam(name = "senderKey", targetNamespace = "http://upg.sbns.bssys.com/")
//        java.lang.String senderKey
    );

    @WebMethod
    @RequestWrapper(localName = "sendRequestsSRP", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.SendRequestsSRP")
    @ResponseWrapper(localName = "sendRequestsSRPResponse", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.SendRequestsSRPResponse")
    @WebResult(name = "return", targetNamespace = "http://upg.sbns.bssys.com/")
    public java.util.List<java.lang.String> sendRequestsSRP(
            @WebParam(name = "requests", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.util.List<java.lang.String> requests,
            @WebParam(name = "sessionId", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String sessionId
    );

    @WebMethod
    @RequestWrapper(localName = "loginSign", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.LoginSign")
    @ResponseWrapper(localName = "loginSignResponse", targetNamespace = "http://upg.sbns.bssys.com/", className = "com.bssys.sbns.upg.LoginSignResponse")
    @WebResult(name = "return", targetNamespace = "http://upg.sbns.bssys.com/")
    public java.util.List<byte[]> loginSign(
            @WebParam(name = "sessionId", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String sessionId,
            @WebParam(name = "clientAuthData", targetNamespace = "http://upg.sbns.bssys.com/")
                    byte[] clientAuthData,
            @WebParam(name = "fraudParams", targetNamespace = "http://upg.sbns.bssys.com/")
                    java.lang.String fraudParams
    );
}
