package com.upg;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-01-27T20:33:28.596+03:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "UniversalPaymentGate",
                  wsdlLocation = "file:upg.wsdl",
                  targetNamespace = "http://upg.sbns.bssys.com/") 
public class UniversalPaymentGate extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://upg.sbns.bssys.com/", "UniversalPaymentGate");
    public final static QName UniversalPaymentGateSbrfImplPort = new QName("http://upg.sbns.bssys.com/", "UniversalPaymentGateSbrfImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:upg.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UniversalPaymentGate.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:upg.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UniversalPaymentGate(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UniversalPaymentGate(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UniversalPaymentGate() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public UniversalPaymentGate(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UniversalPaymentGate(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UniversalPaymentGate(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns UniversalPaymentGateSbrf
     */
    @WebEndpoint(name = "UniversalPaymentGateSbrfImplPort")
    public UniversalPaymentGateSbrf getUniversalPaymentGateSbrfImplPort() {
        return super.getPort(UniversalPaymentGateSbrfImplPort, UniversalPaymentGateSbrf.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UniversalPaymentGateSbrf
     */
    @WebEndpoint(name = "UniversalPaymentGateSbrfImplPort")
    public UniversalPaymentGateSbrf getUniversalPaymentGateSbrfImplPort(WebServiceFeature... features) {
        return super.getPort(UniversalPaymentGateSbrfImplPort, UniversalPaymentGateSbrf.class, features);
    }

}
